from typing import TypedDict

from langgraph.graph import StateGraph, END

from src.rag_engine import ask_interview_assistant
from src.career_coach import generate_career_plan
from src.ml_agent import ml_agent

# ------------------------------------
# STATE
# ------------------------------------

class AgentState(TypedDict):
    query: str
    profile: dict
    readiness_score: float
    response: str

# ------------------------------------
# ROUTER
# ------------------------------------

def router(state):

    query = state["query"].lower()

    placement_keywords = [
        "predict my placement",
        "placement prediction",
        "placement readiness score",
        "readiness score",
        "evaluate my profile",
        "assess my profile",
        "placement probability",
        "chance of placement",
        "am i placement ready",
        "how ready am i",
        "predict readiness",
        "calculate readiness",
        "check my readiness"
    ]

    career_keywords = [
        "career",
        "resume",
        "roadmap",
        "job",
        "internship",
        "skill",
        "improve",
        "prepare",
        "study plan",
        "learning path",
        "certification",
        "linkedin",
        "project"
    ]

    if any(keyword in query for keyword in placement_keywords):
        return "placement_agent"

    if any(keyword in query for keyword in career_keywords):
        return "career_agent"

    return "interview_agent"

# ------------------------------------
# ML AGENT
# ------------------------------------
def placement_agent(state):

    profile = state.get("profile")

    if not profile:
        return {
            "response":
            "Please complete the Readiness Predictor first."
        }

    result = ml_agent(profile)

    score = result["readiness_score"]

    return {
        "readiness_score": score,
        "response": f"""
    # Placement Readiness Analysis

    Placement Readiness Score: {score}%

    Your profile has been evaluated successfully.

    Use the Career Coach for detailed recommendations.
    """
    }
# ------------------------------------
# INTERVIEW AGENT
# ------------------------------------

def interview_agent(state):

    answer = ask_interview_assistant(
        state["query"]
    )

    return {
        "response": answer
    }


# ------------------------------------
# CAREER AGENT
# ------------------------------------

def career_agent(state):

    report = generate_career_plan(
        profile={},
        readiness_score=80,
        skills="Python, SQL",
        target_role="Data Analyst",
        target_company="TCS"
    )

    return {
        "response": report
    }


# ------------------------------------
# REPORT AGENT
# ------------------------------------

def report_agent(state):

    return {
        "response":
        state["response"]
        + "\n\n---\nGenerated by InterviewPilot AI Agent"
    }


# ------------------------------------
# GRAPH
# ------------------------------------

graph = StateGraph(AgentState)

graph.add_node(
    "placement_agent",
    placement_agent
)

graph.add_node(
    "interview_agent",
    interview_agent
)

graph.add_node(
    "career_agent",
    career_agent
)

graph.add_node(
    "report_agent",
    report_agent
)

graph.add_conditional_edges(
    "__start__",
    router,
    {
        "placement_agent": "placement_agent",
        "interview_agent": "interview_agent",
        "career_agent": "career_agent"
    }
)

graph.add_edge(
    "placement_agent",
    "report_agent"
)

graph.add_edge(
    "interview_agent",
    "report_agent"
)

graph.add_edge(
    "career_agent",
    "report_agent"
)

graph.add_edge(
    "report_agent",
    END
)

agent_graph = graph.compile()